server:
 port: ${PORT:0}
spring: 
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER 
 application: 
  name: service-microfono
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka
 instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}